exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("recipes")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("recipes").insert([
        {
          id: 1,
          title: "Vanilla Bean Ice Cream",
          description: "The easiest homemade ice cream recipe ever.",
          serves: "4-6",
          prep_time: "4 hours-Overnight",
          cook_time: "N/A",
          ingredients: JSON.stringify([
            "1 (14 oz) can sweetened condensed milk",
            "1 tablespoon (15g) vanilla bean paste",
            "2 cups (475g) heavy cream cold",
          ]),
          method: JSON.stringify([
            "In a chilled metal bowl whisk together the sweetened condensed milk and the vanilla bean paste. Set aside in the freezer.",
            "In a chilled bowl of a stand mixer whip the heavy cream until stiff peaks form 7-8 minutes.",
            "Once soft peaks form get the sweetened condensed milk mixture from the freezer and gently fold ¾ of the whipped cream into the sweetened condensed milk and vanilla bean mixture. You want to let your rubber spatula hit the bottom of the bowl and then raise it up as you fold and spin the bowl keeping the whipped cream airy and light. Add a pinch of salt and mix to combine. Finally fold in the remaining whipped cream.",
            "When the mixture is fully combined place into a 9x5 loaf pan and gently press some plastic wrap directly on top of the whipped mixture. Place into the freezer until fully frozen at least 4 hours preferably overnight. Serve and enjoy.",
          ]),
          category: "Dessert",
          rating: 4.5,
          image_path:
            "https://www.yourhomebasedmom.com/wp-content/uploads/2017/07/vanilla-ice-cream-recipe-squarejpg-480x270.jpg",
        },
        {
          id: 2,
          title: "Brown Butter Rice Krispies Treats",
          description:
            "The easiest 3-ingredient Rice Krispies Treats recipe ever.",
          serves: "8-10",
          prep_time: "5 minutes, plus 1 hour cooling",
          cook_time: "8 minutes",
          ingredients: JSON.stringify([
            "1 cup (224g) salted butter, plus extra for greasing the pan",
            "2x (40oz) bags mini marshmallows",
            "8 ½ cups (238g) crispy rice cereal (Rice Krispies preferred)",
          ]),
          method: JSON.stringify([
            "In a large stock pot set over medium heat, brown the butter, stirring often and watching closely so it does not burn, about 8-10 minutes.",
            "Once the butter is browned, stir in the marshmallows a few handfuls at a time. Make sure each batch is melted and emulsified before adding the next handful.",
            "Fold in the crispy rice cereal and make sure to evenly coat the cereal with the brown butter marshmallows.",
            "Generously grease a non-stick 9x13 baking pan. Press the marshmallow-rice cereal mixture into the pan and set aside to cool, about an hour, and then slice and serve.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "https://saltandbaker.com/wp-content/uploads/2021/01/salted-brown-butter-rice-krispie-treats-square.jpg",
        },
        {
          id: 3,
          title: "Mac and Cheese",
          description:
            "So easy, you may never make boxed mac and cheese again.",
          serves: "4",
          prep_time: "5 minutes",
          cook_time: "15 minutes",
          ingredients: JSON.stringify([
            "4 cups (950mL) half and half",
            "1 cup (240ml) water",
            "1 lb (453g) elbow macaroni",
            "2 cups (180g) shredded cheddar cheese, freshly grated",
          ]),
          method: JSON.stringify([
            "In a 6-8 quart stock pot, bring the half and half and water to a boil and season with salt. Add the elbow macaroni and cook until al dente per package directions, about 7-9 minutes.",
            "Turn off the heat and add in the shredded cheese, stirring to melt the cheese and coat the pasta. Check seasoning, add salt to taste if necessary, and enjoy.",
          ]),
          category: "Main Course",
          rating: 4.5,
          image_path: "https://www.allrecipes.com/thmb/e8uotDI18ieXNBY0KpmtGKbxMRM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/238691-Simple-Macaroni-And-Cheese-mfs_008-4x3-6ed91ba87a1344558aacc0f9ef0f4b41.jpg",
        },
        {
          id: 4,
          title: "Chicken Teriyaki",
          description: "The easiest chicken teriyaki recipe ever.",
          serves: "4",
          prep_time: "5 minutes",
          cook_time: "15 minutes",
          ingredients: JSON.stringify([
            "2 lbs (906g) boneless skin-on chicken thighs, skin removed and set aside for rendering",
            "1 cup (240ml) dark soy sauce",
            "1 cup (240ml) honey",
          ]),
          method: JSON.stringify([
            "In a large non-stick skillet set over medium heat, add the chicken skins to the pan to render the fat. This will be your cooking oil. Once you have 1-2 tablespoons of fat in the pan, remove the skin.",
            "Turn the heat to medium-high and sear the chicken thighs until golden brown, about 2-3 minutes, flip and cook for another 2-3 minutes. The thighs do not have to be cooked through.",
            "Remove the chicken from the pan and turn off the heat. Cut the thighs into cubes and then add them back to the pan and turn the heat to medium. Pour in your soy sauce and honey and gently stir until combined. Raise the heat to medium-high and bring the skillet to a boil. Then lower the heat to medium and let the mixture simmer and reduce, occasionally mixing, until it glazes and coats the chicken, about 15 minutes. Optionally garnish with sesame seeds and serve with rice and enjoy.",
          ]),
          category: "Main Course",
          rating: 4.5,
          image_path: "https://modernmealmakeover.com/wp-content/uploads/2020/10/IMG_6548-4.jpg",
        },
        {
          id: 5,
          title: "Pancakes",
          description: "The easiest pancake recipe ever.",
          serves: "2-4",
          prep_time: "10 minutes",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "2 ripe bananas, broken into pieces",
            "3 large eggs",
            "½ -⅔ cup (75g) all-purpose flour",
            "Pinch of salt",
          ]),
          method: JSON.stringify([
            "To a blender, add the bananas and eggs and blend on high. Then add the flour and salt. Blend on medium until combined. If the batter seems too thick you can add a bit of water. If the batter is too runny, add a bit more flour. Let the batter rest for 2-3 minutes.",
            "Heat a large non-stick pan over medium heat. Once hot, use a 1/3rd cup measuring cup to pour batter for each pancake and cook until set, about 3-4 minutes. Flip and finish cooking on the other side for another 2-3 minutes. Serve and enjoy.",
          ]),
          category: "Breakfast",
          rating: 4.5,
          image_path: "https://handletheheat.com/wp-content/uploads/2019/02/The-Best-Pancake-Recipe-SQUARE.jpg",
        },
        {
          id: 6,
          title: "Banana Bread",
          description: "The easiest 3-ingredient banana bread ever.",
          serves: "6-8",
          prep_time: "10 minutes",
          cook_time: "55 minutes, plus cooling",
          ingredients: JSON.stringify([
            "3 very ripe bananas",
            "2 large eggs",
            "1 box, fancy yellow cake mix",
          ]),
          method: JSON.stringify([
            "Preheat your oven to 350°F (176°C). In a large mixing bowl, mash the bananas with a handheld mixer. Add the eggs and mix until combined, then whisk in the cake mix until fully combined.",
            "Into a parchment paper-lined 9” x 5” non-stick loaf pan, pour in the batter and bake for 45-50 minutes, or until a toothpick or cake tester comes out clean. Let the cake cool and then slice and enjoy.",
          ]),
          category: "Bread",
          rating: 4.5,
          image_path: "https://joyfoodsunshine.com/wp-content/uploads/2019/03/best-banana-bread-recipe-1x1-2-500x375.jpg",
        },
        {
          id: 7,
          title: "Mozzarella Sticks",
          description: "The easiest homemade mozzarella sticks recipe ever.",
          serves: "3-4",
          prep_time: "2 hours",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "10 spring roll wrappers",
            "10 mozzarella string cheese sticks, frozen for 1-2 hours",
            "Water, to seal the wrappers around the cheese sticks",
            "2 quarts (2L) vegetable oil",
          ]),
          method: JSON.stringify([
            "Begin by preheating your oil in a heavy bottomed pot or Dutch oven to 350°F (176°C).",
            "While the oil is heating, unwrap the spring roll wrappers and cover with a damp towel to keep them from drying out. Lay one wrapper in front of you like a diamond. Place the cheese stick on the bottom third of the wrapper, fold in the sides and then roll tightly. Right before the final roll, take your finger and dip in water and run it over the last edge before finishing the wrapping. This will help the wrapper stay sealed.",
            "Once you have all 10 cheese sticks wrapped, gently drop each stick into your hot oil in batches, being careful not to overcrowd. Use a spider to flip each stick so all sides are fried. Fry for 3-4 minutes or until golden brown, and transfer the fried cheese sticks to a wire rack lined baking tray and season with salt.",
          ]),
          category: "Appetizer",
          rating: 4.5,
          image_path: "https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_860,ar_3:2/v1/img/recipes/30/97/7/7GmgWw4TTUCCw7xGKQAP_0S9A6434.jpg",
        },
        {
          id: 8,
          title: "Mashed Potatoes",
          description: "The easiest homemade mashed potatoes recipe ever.",
          serves: "4",
          prep_time: "5 minutes",
          cook_time: "15-20 minutes",
          ingredients: JSON.stringify([
            "2 lbs (906g) Yukon Gold potatoes, peeled and cut into 1-inch pieces",
            "Salt to taste",
            "½ cup (120ml) half and half",
            "1 cup (224g) unsalted butter",
          ]),
          method: JSON.stringify([
            "To a 6-8 quart stock pot, bring your potatoes to a boil in heavily salted water, around 15-20 minutes or until fork tender.",
            "While the potatoes cook, to a small saucepan combine half and half and butter and cook over medium heat until the butter is completely melted and hot. Keep warm until potatoes are cooked.",
            "Once the potatoes are done cooking, strain and drain thoroughly. The drier the potato, the more cream and butter it can absorb. While your potatoes are still hot, into your stock pot, press the potatoes through a potato ricer on the finest setting. You can also return the potatoes to the stock pot and mash them with a hand masher.",
            "Whisk your melted butter and half and half into the mashed potatoes until fully combined. Taste for seasoning and add more salt if necessary. Serve and enjoy.",
          ]),
          category: "Side Dish",
          rating: 4.5,
          image_path: "https://www.marthastewart.com/thmb/IgzUVbViUGURRlp6aQDB_iXAd9Y=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/MSL-341854-Perfect-Mashed-Potatoes-Beauty-horiz-0923-2de5512528784a42b42e57871cac1caf.jpg",
        },
        {
          id: 9,
          title: "Sausage Date Bites",
          description: "The easiest fancy appetizer recipe ever.",
          serves: "4",
          prep_time: "15 minutes",
          cook_time: "20 minutes",
          ingredients: JSON.stringify([
            "½ lb (226g) Longanisa sausage, removed from the casings",
            "12oz (340g) dates, pitted and split on one side",
            "8-10 bacon slices",
          ]),
          method: JSON.stringify([
            "Stuff each date with a spoonful of the sausage.",
            "Wrap each date with a slice of bacon. Pin the bacon shut by threading a toothpick through the date and the bacon.",
            "Into an aluminum foiled-lined air fryer set at 325°F (163°C), place the dates seam side down and air fry for 15-20 minutes, or until bacon is cooked and crispy.",
          ]),
          category: "Appetizer",
          rating: 4.5,
          image_path: "https://static.wixstatic.com/media/10e36c_73ad79d0d18a43afb4c3399e466e2bf1~mv2.jpg/v1/fill/w_640,h_364,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/10e36c_73ad79d0d18a43afb4c3399e466e2bf1~mv2.jpg",
        },
        {
          id: 10,
          title: "Tomato Soup",
          description: "The easiest and most delicious soup recipe ever.",
          serves: "2-4",
          prep_time: "5 minutes",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "½ cup (112g), plus 4 tablespoons (57g) unsalted butter",
            "1 small yellow onion, sliced",
            "1 (28 oz) can whole peeled San Marzano tomatoes, hand crushed",
            "1 cup (240g) water",
            "Salt, to taste",
          ]),
          method: JSON.stringify([
            "To a 4-quart saucepan over medium heat, add your ½ cup of butter and cook until melted. Add the onions, season with salt and cook until soft, about 3-4 minutes.",
            "Add the crushed tomatoes with their liquid and a cup of water. Set to medium-high heat and bring to a boil. Once boiling, reduce heat to medium and simmer until the onions are nearly falling apart, about 10-15 minutes.",
            "It’s not necessary to make the soup any smoother, but if you want it extra smooth, use an immersion blender to puree the soup. Check for salt and season to taste accordingly. Add 2 tablespoons of butter and mix (or continue blending) until combined. Plate your soup and melt your remaining 2 tablespoons of butter to spoon over the top. Serve immediately and enjoy.",
          ]),
          category: "Soup",
          rating: 4.5,
          image_path: "https://www.allrecipes.com/thmb/QijITeBBcE99Ur5kDoccAJ35WWo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/277311spicy-fresh-tomato-soupFranceC4x3-56454ad082214f33960f62665fc8c169.jpg",
        },
        {
          id: 11,
          title: "Spicy Chili Crisp Compound Butter",
          description: "The easiest 3-ingredient compound butter recipe ever.",
          serves: "4",
          prep_time: "5 minutes",
          cook_time: "N/A",
          ingredients: JSON.stringify([
            "1 cup (224g) salted butter, softened",
            "4 cloves garlic, grated",
            "¼ cup (60g) spicy chili crisp, mostly the solids",
          ]),
          method: JSON.stringify([
            "In a food processor, or with a handheld mixer, combine all ingredients, mix until combined.",
            "Place a sheet of plastic wrap down on a work surface and spread the butter into a seven-inch long strip on the lower third of the plastic wrap. Roll the plastic wrap around the butter into a thick log, fully enclosing it in the plastic wrap, pressing out any air bubbles as you go. Spin and roll up like a sausage, twisting the ends to secure and place in the fridge until solid.",
            "Once solid, you can cut rounds and place on anything you like such as steak, rice, eggs, roasted vegetables.",
          ]),
          category: "Condiment",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 12,
          title: "Simple Crusty Bread",
          description: "The easiest homemade bread recipe ever.",
          serves: "4-6",
          prep_time: "30 minutes, plus 8-hour proof and cooling",
          cook_time: "45 minutes",
          ingredients: JSON.stringify([
            "1 ¼ cups (315g) water, lukewarm (90-100°F, 32-37°C)",
            "3/4 teaspoon (5g) active dry yeast",
            "3 cups (450g) bread flour",
            "1 ½ teaspoons (6g) fine sea salt",
          ]),
          method: JSON.stringify([
            "In a large mixing bowl, add your flour and salt and mix by hand to combine.",
            "In a separate bowl, or directly in your measuring cup, mix the yeast into the water until combined. Make sure you see some foam to know your yeast is alive.",
            "Pour the yeasty water into your dry ingredients and using your hands in the shape of a claw, mix until combined and a shaggy dough has formed. It may be stickier than you are used to, but keep mixing until all the flour is absorbed.",
            "Cover the bowl tightly with plastic wrap and keep at room temperature for 8 hours to let it rise.",
            "Place a large Dutch oven or cast iron pot into the oven and heat at 500°F (260°C) for 30 minutes or up to an hour. Remove your pot from the oven and dust the bottom with flour. Carefully place your dough ball in the pot, being very careful not to burn yourself.",
            "Place the lid on the pot and bake for 20-25 minutes. Then reduce the oven temperature to 425°F (218°C) and bake for 15-20 minutes more or until deeply browned.",
            "Remove and allow to cool completely before cutting and enjoying.",
          ]),
          category: "Bread",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 13,
          title: "Nutella Pretzel Milkshake",
          description: "The easiest & best milkshake recipe upgrade ever.",
          serves: "1",
          prep_time: "5 minutes",
          cook_time: "N/A",
          ingredients: JSON.stringify([
            "2 cups (360g) vanilla ice cream",
            "¼ cup (70g) Nutella, plus more for garnish",
            "2 pretzel rods, 1 in the milkshake, 1 for garnish",
          ]),
          method: JSON.stringify([
            "In a blender, combine the ice cream, one pretzel rod, and your Nutella and blend. Start on low until it begins to come together and then increase the speed to high until combined.",
            "Pour the milkshake into a glass and dip your other pretzel rod into your container of Nutella and place it, Nutella side down, in your milkshake for a nice surprise. Serve and enjoy.",
          ]),
          category: "Beverage",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 14,
          title: "Bean and Cheese Burrito",
          description: "The easiest 3-ingredient bean & cheese burrito ever.",
          serves: "1",
          prep_time: "5 minutes",
          cook_time: "6 minutes",
          ingredients: JSON.stringify([
            "1/4-1/2 cup (57-114g) beans, leftover from your favorite Mexican spot (I used refried black beans)",
            "1 cup (90g) Monterey Jack cheese, freshly grated",
            "1 Large burrito-sized flour tortilla",
          ]),
          method: JSON.stringify([
            "Heat the tortilla over an open flame for 30 seconds per side to soften.",
            "Lay down the tortilla, place the beans on the lower third of the tortilla. Cover with cheese. Fold in the edges and roll from the bottom tightly.",
            "Heat a 10-inch skillet over medium heat add your burrito seam side down, heat for 2-3 minutes or until toasted.",
            "Flip and toast the other side for 2-3 minutes, or until heated through. Serve and enjoy.",
          ]),
          category: "Main Course",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 15,
          title: "Spicy Avocado Toast",
          description:
            "The easiest 3-ingredient spicy avocado toast recipe ever.",
          serves: "1-2",
          prep_time: "2 minutes",
          cook_time: "3 minutes",
          ingredients: JSON.stringify([
            "1 ripe avocado, pit removed, thinly sliced",
            "Salt, to taste",
            "2 slices sourdough boule, sliced ½-inch thick and toasted",
            "Spicy chili crisp, to taste",
          ]),
          method: JSON.stringify([
            "Toast two slices of your favorite bread until golden.",
            "Halve your avocado, remove the pit and cut into fourths. Then using your fingers peel off the skins and thinly slice. Let your knife slice through and don’t press down on the avocado or it will mash and bruise.",
            "Fan out the avocado on top of your toasted bread, season with salt and drizzle as much chili crisp as you can handle. Serve and enjoy.",
          ]),
          category: "Breakfast",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 16,
          title: "Peanut Butter Cinnamon Toast Crunch Bites",
          description: "Just go make these and thank me later.",
          serves: "8-10",
          prep_time: "5 minutes, plus cooling",
          cook_time: "5 minutes",
          ingredients: JSON.stringify([
            "1 ½ cups (510g) honey (wildflower or another mild honey)",
            "1 ½ cups (375g) salted creamy peanut butter",
            "4 cups (160g) Cinnamon Toast Crunch",
          ]),
          method: JSON.stringify([
            "To a 4-quart saucepan over low heat, add the honey and peanut butter and cook over until warmed through and thoroughly combined, about 3-5 minutes.",
            "Fold in Cinnamon Toast Crunch and coat the cereal in the peanut butter and honey mixture.",
            "Pour the mixture into a 9x5 loaf pan lined with parchment paper and let it cool before cutting into your desired shape and serving.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 17,
          title: "Jalapeno Poppers",
          description: "Jalapeño poppers have never been this easy.",
          serves: "4",
          prep_time: "15 minutes",
          cook_time: "25 minutes",
          ingredients: JSON.stringify([
            "15 large jalapeños, de-stemmed, halved, seeds and ribs removed",
            "1 lb (453g) creamy herbed goat cheese (recommended Boursin)",
            "2 lbs bacon (906g), cut in half",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 450°F (232°C).",
            "Stuff each jalapeño half with roughly 2 teaspoons of cheese. Wrap the stuffed pepper in a piece of bacon, twisting it up and around the jalapeño while trying to keep the bacon in a single layer. Trim any excess bacon if necessary.",
            "Place the wrapped jalapeños, stuffed side up, on a parchment lined sheet tray and bake for 20-25 minutes, or until the bacon is crispy and cooked through. Let them cool enough to handle and then serve and enjoy.",
          ]),
          category: "Appetizer",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 18,
          title: "Fettuccine Al Burro Pasta",
          description:
            "The easiest 3-ingredient Fettuccine Al Burro recipe ever.",
          serves: "4",
          prep_time: "5 Minutes",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "½ cup (112g) Salted Butter, cubed",
            "1 cup (118g) Parmigiano Reggiano, finely grated",
            "1 lb (453g) Fettuccine",
          ]),
          method: JSON.stringify([
            "Place fettuccine in a large 6-8 quart pot of boiling water that has been seasoned generously with salt. Cook according to package instructions or until cooked al dente, about 7 minutes. Drain the pasta but reserve ½ cup of the pasta water.",
            "Return the pasta to the pot, or transfer to a saucier pot, and add the butter, tossing vigorously and continuously until emulsified. You can adjust with leftover pasta water as needed. Once emulsified, add the Parmigiano Reggiano, toss to combine, and turn off the heat. Add some of the cooking water if needed. Season with salt to taste and add more butter and cheese as needed. Serve and enjoy.",
          ]),
          category: "Main Course",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 19,
          title: "Biscuits",
          description: "The easiest 3-ingredient biscuits ever.",
          serves: "4",
          prep_time: "15 minutes",
          cook_time: "10-15 minutes",
          ingredients: JSON.stringify([
            "2 cups (300g) self-rising flour, plus more for dusting your work surface",
            "½ cup (112g) butter, cubed and cold",
            "1 cup (236 mL) heavy whipping cream",
            "Salt to taste",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 450°F (230°C). To a large bowl add your flour and butter, and using a pastry blender or a fork, cut the butter into the flour until you get pea-size balls. Then using a fork, stir in the heavy whipping cream. As soon as you get a rough-shaggy dough, place it onto a work surface and lightly knead it until it comes together and is not sticking to the work surface.",
            "Gently roll your dough into a rough ½-inch thick rectangle, fold it into thirds that overlap (like a trifold), then roll it out one more time until you get a rectangle that is roughly 1/2 of an inch. Using a pastry brush, brush off any excess flour and then with a cookie cutter or glass, press out (don’t twist) your biscuits.",
            "Place the biscuits in a cast iron pan side by side, you want them touching as this helps them rise, and bake for 8-12 minutes or until golden and cooked through. Serve and enjoy.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 20,
          title: "Brownie Cookies",
          description: "The easiest 3-ingredient Brownie Cookie recipe ever.",
          serves: "4",
          prep_time: "10 minutes",
          cook_time: "12 minutes",
          ingredients: JSON.stringify([
            "1¼ cups (144g) powdered sugar",
            "⅓ cup (30g) cocoa powder",
            "2 large eggs, whites only",
            "½ teaspoon (3g) fine sea salt",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 325°F (162°C).",
            "To a large mixing bowl add powdered sugar and cocoa powder and combine using a hand mixer. Add in your egg whites and salt and continue beating together until fully combined.",
            "To a parchment paper lined sheet tray, spoon the batter with a spoon, 1-2 tablespoons per cookie. Leaving 1 ½-2 inches between each cookie. Around 8 cookies per sheet tray.",
            "Bake for 10-12 minutes. Cool on a wire rack. Serve and enjoy.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 21,
          title: "Kettle Corn",
          description: "Maybe the easiest salty-sweet popcorn recipe ever.",
          serves: "2",
          prep_time: "5 minutes",
          cook_time: "5 minutes",
          ingredients: JSON.stringify([
            "Salt, to taste",
            "3 tablespoons (36g) sugar",
            "2 tablespoons (30g) vegetable oil",
            "¼ cup (56g) corn kernels",
          ]),
          method: JSON.stringify([
            "To a blender, add the desired amount of kosher salt and the sugar and blend on high speed until it turns to powder.",
            "To a 6-quart pot set over medium-high heat, add the vegetable oil and heat until just smoking. Add the popcorn kernels and sugar/salt mixture and top with a lid.",
            "Continuously and vigorously shake the pot, holding the lid down, until the popping begins to subside, about 3-4 minutes.",
            "Pour into a serving bowl and enjoy.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 22,
          title: "Potato Chips",
          description: "The easiest homemade potato chip recipe ever.",
          serves: "4",
          prep_time: "20 minutes",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "1-2 large Russet potatoes, peeled",
            "3 quarts (2.8L) vegetable oil for frying",
            "3 ⅓ cup (800g) water, for brine",
            "2 teaspoons (12g) fine sea salt, for brine",
            "Mayonnaise for dipping",
            "Salt, to taste",
          ]),
          method: JSON.stringify([
            "To make your brine, fill a large bowl with water and add your sea salt. Let sit for 10-15 minutes.",
            "Slice the potatoes directly into the brine on the lowest setting of a mandoline. Using your hands, toss the potato slices around in the brine to make sure they don’t stick together. Let sit for 10-15 minutes.",
            "While the potatoes are brining, begin to heat canola oil in a heavy bottomed pot or dutch oven to 350°F (176°C).",
            "Transfer the sliced potatoes from the brine and lay them out in a single layer onto a paper towel lined baking sheet. Using another piece of paper, pat the chips dry.",
            "Working in batches, add the potatoes to the hot oil, making sure to move them constantly, this will help the chips cook more evenly.",
            "Once the chips are golden brown and crispy, use a spider to remove the chips from the hot oil, giving them a moment to drain themselves of excess oil before transferring them to a large mixing bowl and seasoning with salt to taste.",
            "Serve with a side of mayo or your favorite sauce for the best chip ever.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 23,
          title: "Tuna Salad",
          description: "The easiest tuna salad recipe ever.",
          serves: "1",
          prep_time: "5 minutes",
          cook_time: "N/A",
          ingredients: JSON.stringify([
            "1 can (7oz or 198g) Albacore tuna, drained",
            "Creamy dill salad dressing, to taste",
            "1-2 small dill pickles, finely chopped (gherkins recommended)",
          ]),
          method: JSON.stringify([
            "Place your tuna into a medium mixing bowl and using a fork, finely shred the tuna as finely as possible. Add in your pickles and dressing and mix together until combined. Season to taste with salt and enjoy.",
          ]),
          category: "Lunch",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 24,
          title: "Japanese Gyudon-Inspired Steak & Onions",
          description: "Maybe the easiest steak recipe ever.",
          serves: "2",
          prep_time: "10 minutes",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "1.5 lbs (680g) ribeye steak, thinly sliced against the grain, fat cap removed and finely chopped",
            "½ yellow onion, thinly sliced",
            "½ cup (60mL) shiro dashi",
            "1 cup (120mL) water",
          ]),
          method: JSON.stringify([
            "Place the fat in a large sauté pan set over medium-low heat and cook until you have about 1-2 tablespoons of fat rendered out. Add the onion and increase the heat to medium-high and saute for 3-4 minutes until softened and just starting to brown. Add the shiro dashi and the water and increase the heat to medium-high and bring to a boil. Reduce the heat to medium-low and add in the thinly sliced steak, stirring to separate the pieces and cook through, about 2-3 minutes. Turn off the heat as soon as the steak is done. Taste for seasoning and add salt if needed. You can eat this as is or serve it as it’s meant to be, over rice and garnished with green onion.",
          ]),
          category: "Dinner",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 25,
          title: "Sugar Cookies",
          description: "The easiest homemade sugar cookie recipe ever.",
          serves: "24 cookies",
          prep_time: "10 minutes",
          cook_time: "15 minutes",
          ingredients: JSON.stringify([
            "1 cup (224g) salted butter, room temperature",
            "1 cup (200g) sugar, plus more for rolling",
            "1 3/4 cups (210g) all-purpose flour",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 325°F (163°C).",
            "To a large mixing bowl add salted butter and using a mixer, beat on high speed until smooth. Continue mixing and add in the sugar and cream until combined. Reduce the mixer speed to low and gradually add your flour and mix until completely incorporated and formed into a dough.",
            "Using your hands, grab 1 ½ tablespoon pieces of dough and roll them into balls.",
            "Place extra sugar into a shallow dish and roll each ball in the sugar to coat.",
            "Evenly place the cookies onto the cookie sheet and press flat using the bottom of a cup, until ¼-⅓ inch thick.",
            "Bake for 14-16 minutes. Let cool before serving.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 26,
          title: "Meatballs",
          description: "The easiest homemade meatball recipe ever.",
          serves: "8 large meatballs",
          prep_time: "10 minutes",
          cook_time: "20 minutes",
          ingredients: JSON.stringify([
            "1 lb (453g) 70% Lean Ground Beef",
            "2 tablespoons (15g) dry mushroom soup mix",
            "1 slice stale bread, chopped",
            "Water, splash",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 450°F (230°C).",
            "In a large bowl mix together the ground beef, soup mix, stale bread, and a splash of water until fully combined. On to a parchment paper-lined sheet tray, divide the mixture into 8 portions and roll into balls.",
            "Bake for 15-20 minutes, or until the meatballs are cooked through and nicely browned on the outside.",
          ]),
          category: "Main Course",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 27,
          title: "Pork Chops and Applesauce",
          description: "The easiest grilled pork chop recipe ever.",
          serves: "1",
          prep_time: "15 minutes",
          cook_time: "10-12 minutes",
          ingredients: JSON.stringify([
            "½ pound, 1-inch thick (about 227g) pork chop, bone-in, nice fat cap",
            "Grill seasoning, to taste (your favorite brand)",
            "Applesauce, the thicker the better",
          ]),
          method: JSON.stringify([
            "Begin to preheat the grill by lighting charcoal. Allow the coals to stop burning and turn white. This should take about 10-15 minutes.",
            "Season the pork chop with salt.",
            "Once the grill is hot and ready, using tongs, rub the grill grates with the fat cap of the pork chop. This will start rendering the fat on the pork and oil your grate at the same time.",
            "Place your pork on the grill and cook for 3-4 minutes, then turn 45 degrees, and cook for another 2-3 minutes. Flip the chop and cook for 2-3 minutes, then turn 45 degrees, and cook for an additional 2-3 minutes. That will get you those classic hatch grill marks. Remove from the heat and allow the pork to rest.",
            "If your applesauce is watery, you can strain it in a fine mesh strainer, but if it is thick enough, you can make a nice quenelle (an egg-shaped dollop) and place it on top of the pork chop immediately before serving. Optionally add half a slice of compound butter such as the 3-ingredient Spicy Chili Crisp butter and place under a broiler on high (or use a chef’s torch) to melt the butter. If you do use the broiler, watch it carefully to make sure you remove the dish the moment you see the butter starting to melt.",
          ]),
          category: "Main Course",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 28,
          title: "Tortillas",
          description: "The easiest homemade flour tortilla recipe ever.",
          serves: "4-6",
          prep_time: "15 minutes, plus 1 hour rest time",
          cook_time: "5 minutes",
          ingredients: JSON.stringify([
            "2 1/4 cups (360g) all-purpose flour, plus extra for dusting work surface",
            "2 teaspoons (8g) fine sea salt",
            "½ cup (96g) vegetable oil",
            "½ cup (120ml) warm water",
          ]),
          method: JSON.stringify([
            "In a medium bowl, add all your ingredients (except the extra flour) and mix with your hand until combined. Once a shaggy dough forms, knead for 2 minutes or until smooth.",
            "Place your dough ball onto your work surface and cover with a damp towel to rest for 10 minutes.",
            "Flour your work surface and once the dough is rested, pinch off ½-inch round balls of dough for taco sized tortillas. Flour the top of the dough ball lightly and then using your hand, flatten the ball into a small disc. Using a rolling pin, gently roll the dough out until paper thin, turning and rolling as you go.",
            "Heat a cast-iron skillet or griddle over medium-high heat (around 350°F/176°C) and cook until the tortilla begins to bubble, about 1 minute, flip and cook for another minute. Stack the tortillas as you cook them and cover them with a towel to keep them warm. Serve and enjoy.",
          ]),
          category: "Side",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 29,
          title: "PB&J",
          description: "Maybe the greatest sandwich recipe of all-time.",
          serves: "1",
          prep_time: "4 minutes",
          cook_time: "N/A",
          ingredients: JSON.stringify([
            "2 slices white bread (Sunbeam preferred)",
            "2-3 tablespoons (32-48g) creamy peanut butter (or crunchy if you prefer)",
            "2 tablespoons (40g) strawberry jelly or jam (Bonne Maman preferred)",
          ]),
          method: JSON.stringify([
            "Take your favorite white bread, your favorite peanut butter, and your best strawberry jam, and layer them up. Slice on the diagonal, serve and enjoy.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 30,
          title: "Quesadilla",
          description: "The easiest homemade quesadilla recipe ever.",
          serves: "1",
          prep_time: "5 minutes",
          cook_time: "5-6 minutes",
          ingredients: JSON.stringify([
            "1x 10-inch flour tortilla",
            "½ cup (52g) Monterey Jack cheese, grated, 2 tablespoons (14g) set aside",
            "½ cup (52g) Cheddar cheese, grated, 2 tablespoons (14g) set aside",
          ]),
          method: JSON.stringify([
            "Pre-heat a non-stick pan or griddle over medium heat. Separately, place the tortilla over an open flame to soften a bit and make pliable.",
            "Fill half your tortilla with the ½ cup of Monterey Jack cheese and the ½ cup of Cheddar cheese. Fold over and press closed.",
            "Place the 4 tablespoons of reserved Monterey Jack and Cheddar cheese directly on your pan or griddle. Place your folded tortilla down onto the shredded cheese, which will create a cheese crust.",
            "Cook until the cheese on the pan or griddle is crisp and using your spatula, scrape aggressively underneath the cheese and flip your tortilla. Cook for another 2-3 minutes until golden brown and the cheese inside is melted. Cut into wedges and enjoy.",
          ]),
          category: "Snack",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 31,
          title: "Strawberry Tart",
          description: "The easiest homemade strawberry tart recipe ever.",
          serves: "4",
          prep_time: "10 minutes",
          cook_time: "20 minutes",
          ingredients: JSON.stringify([
            "16 oz (453g) Strawberries, hulled and sliced into rounds",
            "3 tablespoons (36g) sugar",
            "1 sheet puff pastry, thawed if frozen (Dufour brand recommended)",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 400°F (204°C).",
            "Roll out the puff pastry to even it out and form a rough rectangle. If you want to trim it to square it up a bit more, you can, but it’s not absolutely necessary.",
            "To a parchment-lined sheet tray, add your sheet of puff pastry. Leaving an inch border around the edges on each side of the rectangle, begin shingling the sliced strawberries in rows to cover the puff pastry. Evenly sprinkle the strawberries with your sugar.",
            "Bake for 12-15 minutes until the pastry is golden brown and cooked through. Let cool slightly before slicing to serve.",
          ]),
          category: "Dessert",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 32,
          title: "Caprese Salad",
          description: "The easiest 3-ingredient Caprese salad recipe ever.",
          serves: "2",
          prep_time: "5 minutes",
          cook_time: "N/A",
          ingredients: JSON.stringify([
            "2 heirloom tomatoes, sliced into ¼-inch thick slices",
            "1 lb (453g) fresh mozzarella, sliced ¼-inch thick slices",
            "Basil oil, to taste",
            "Salt, to taste",
          ]),
          method: JSON.stringify([
            "Slice the tomatoes and mozzarella into the same width and layer them on a plate. Generously dress them with your basil oil and salt. Serve and enjoy.",
          ]),
          category: "Salad",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 33,
          title: "Prosciutto-Wrapped Cantaloupe Crudo",
          description: "The easiest 3-ingredient cantaloupe crudo recipe ever.",
          serves: "2",
          prep_time: "5 minutes, plus marinade time 1 hour",
          cook_time: "N/A",
          ingredients: JSON.stringify([
            "½ cantaloupe, peeled and sliced into ½ wedges",
            "2 Navel oranges, zest and juice",
            "4 slices prosciutto (or mortadella)",
          ]),
          method: JSON.stringify([
            "Halve the cantaloupe lengthwise, scoop out seeds and discard, remove the rind and slice into ½-inch wedges. For ease of eating, I like to cut the peel off at this point, removing any green or white pith.",
            "Place the cantaloupe wedges into a baking dish and pour the orange juice over them and then sprinkle the wedges evenly with the orange zest. Cover and refrigerate for at least one hour or ideally overnight.",
            "To plate, wrap one slice of prosciutto around each cantaloupe wedge and spoon the remaining marinade around the bottom of the plate. Optionally top your wedges with additional orange zest.",
          ]),
          category: "Appetizer",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 34,
          title: "Garlicky Lemony Cabbage Side Dish",
          description:
            "The easiest and most flavorful cabbage side dish recipe ever.",
          serves: "4",
          prep_time: "10 minutes",
          cook_time: "6 minutes",
          ingredients: JSON.stringify([
            "¼ cup (53g) garlic oil",
            "3 cups green cabbage, quartered, cored and thinly sliced",
            "1 lemon, juice and zest",
            "Salt to taste",
          ]),
          method: JSON.stringify([
            "In a large saute pan set over high heat, add the garlic oil. Once hot, add the sliced cabbage. Toss to coat and char cabbage until brown, about 5-6 minutes.",
            "Season with salt and lemon juice and zest. Taste and add more garlic oil if desired.",
            "To serve, use a carving fork and twist the cabbage as you would pasta and plate.",
          ]),
          category: "Side",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 35,
          title: "Buttered Noodles",
          description: "The easiest 3-ingredient buttered noodles recipe ever.",
          serves: "4",
          prep_time: "N/A",
          cook_time: "10-12 minutes",
          ingredients: JSON.stringify([
            "1 cup (224g) unsalted butter, cubed",
            "1 lb (453g) spaghetti",
            "Salt to taste",
            "Freshly ground black pepper, to taste (optional)",
            "Flaky salt, to taste (optional)",
          ]),
          method: JSON.stringify([
            "Place bucatini in a large pot of boiling water that has been seasoned generously with salt. Cook according to package instructions or until cooked al dente, about 7 minutes. Do not drain the pasta.",
            "While noodles are boiling, to a large saucepan over medium-low heat add half your butter. Once butter is slightly melted, cut off the heat and wait for your pasta to finish boiling.",
            "Using tongs transfer your cooked pasta directly from the pot of water into your melted butter saucepan. Don’t worry about pasta water getting into the pan as it helps to emulsify the sauce. Add your remaining butter and begin constantly tossing the pasta while adding a tablespoon of pasta water at a time until your sauce is fully emulsified and slightly thickened. Ideally you want it clinging to the pasta nicely.",
            "Season to taste with salt, toss again to coat evenly, and serve. Optionally, add flakey salt and freshly cracked pepper. Be cautious when using flaky salt as it could over salt your dish if it’s already salty enough.",
          ]),
          category: "Main Course",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 36,
          title: "Omelette Au Fromage",
          description: "The easiest cheese omelette recipe ever.",
          serves: "1",
          prep_time: "5 minutes",
          cook_time: "5 minutes",
          ingredients: JSON.stringify([
            "1 ½ tablespoons (21g) unsalted butter",
            "3 large brown eggs",
            "⅓ cup (30g) Gruyere cheese, grated",
            "Salt, to taste",
          ]),
          method: JSON.stringify([
            "Add butter to a medium non-stick pan over medium heat. While the butter melts, add eggs to a small mixing bowl, season with salt to taste, and whisk until homogenous.",
            "Once the butter is melted and bubbling, add the eggs to the pan. As the eggs begin to set, continuously pull the edges of the eggs into the center of the pan, ensuring to tilt the pan and fill the emptied space with eggs during this process.",
            "Once the eggs are cooked about 90 percent, add cheese to one half and fold the omelette onto itself. Optionally, if you’d like to toast the omelette, add additional butter to the pan and increase the heat slightly, and gently tilt the pan in the direction of the omelette to toast the bottom and get more color.",
            "Carefully add your omelette to your plate. Serve and enjoy.",
          ]),
          category: "Breakfast",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 37,
          title: "Hazelnut Praline",
          description: "Maybe the easiest candied nuts recipe ever.",
          serves: "4",
          prep_time: "5 minutes",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "½ cup (71g) hazelnuts, toasted and skinned",
            "⅔ cup (130g) sugar",
            "3 tablespoons (45ml) water",
            "1 teaspoon (5ml) lemon juice",
            "Salt, to taste",
          ]),
          method: JSON.stringify([
            "In a small dry skillet set over medium heat, toast the nuts until fragrant and lightly brown and the skin begins to break away from the nut, about 4-5 minutes. Remove the nuts from the pan onto a kitchen towel and roll the nuts in the towel to remove the skins. Set aside while you make the caramelized sugar.",
            "In a small sauce pot combine the sugar, water and lemon juice. Bring to a boil and cook until the sugar begins to turn slightly amber, about 7-9 minutes.",
            "To make the praline, place the hazelnuts onto a silicone mat, and once the sugar is caramelized, pour it over the nuts and allow the mixture to cool completely.",
            "Once cool you can break it apart into large chunks and eat immediately.",
          ]),
          category: "Dessert",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 38,
          title: "Corn Pone with Bacon & Honey",
          description: "The easiest 3-ingredient corn pone recipe ever.",
          serves: "4",
          prep_time: "10 minutes",
          cook_time: "20 minutes",
          ingredients: JSON.stringify([
            "2 cup (644g) medium stone ground cornmeal",
            "Salt, to taste",
            "1 cup (240ml) hot water",
            "½ lb (226g) applewood bacon, fat reserved for cooking",
            "Honey to drizzle",
          ]),
          method: JSON.stringify([
            "In a large bowl, using a spoon, mix cornmeal, salt and hot water and let it rest until all the liquid is absorbed and a thick dough is formed, about 15-20 minutes.",
            "To cook your bacon, to a large cast iron pan to medium heat, add the bacon and cook, flipping each piece for an even cook, until ¼-½ cup of bacon fat is rendered out, about 8-12 minutes. Turn off the heat, drain the bacon on a paper towel-lined plate and chop for garnish. Leave the bacon fat in your pan while you form your corn patties.",
            "To make your corn patties, use your hands to divide the dough into 6 portions, and flatten each portion to ¼-inch thick rounds. Optionally, use a ring mold instead if you have it.",
            "Over medium heat, bring your bacon fat back to temp and fry the corn patties on one side until golden brown, about 4 minutes. Then flip each patty and cook until golden brown, another 3-4 minutes.",
            "Drain the corn patties on a wire rack over a paper towel-lined sheet tray, and season with salt immediately. Before serving, top with chopped bacon and drizzle with honey. Serve and enjoy.",
          ]),
          category: "Side",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 39,
          title: "Pigs in a Blanket",
          description: "The easiest pigs in a blanket recipe upgrade ever.",
          serves: "4-6",
          prep_time: "5 minutes, plus thawing puff pastry 4 hours",
          cook_time: "15-18 minutes",
          ingredients: JSON.stringify([
            "4 kielbasa sausages",
            "1 cup (90g) cheddar cheese, shredded",
            "1 box puff pastry, thawed 4 hours (or overnight) in the fridge",
            "Water, for sealing pastry dough",
          ]),
          method: JSON.stringify([
            "Preheat your oven to 400°F (204°C).",
            "On a cutting board, lay out your thawed puff pastry and cut into rectangles (4 strips) wide enough to leave a ½-inch of exposed sausage on each end.",
            "Onto the center of each strip of puff pastry, place a tablespoon of cheese. Place a piece of Kielbasa on top of the cheese. Wrap the sausage in the puff pastry, but before you close the pastry, dab your finger in water and lightly brush the top edge of the dough where it would seal. Cut off any excess dough and close the pastry. Place it seam side down on a sheet tray.",
            "Bake for 15-18 minutes, or until golden brown. Serve and enjoy.",
          ]),
          category: "Appetizer",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 40,
          title: "Pan Con Tomate",
          description: "Maybe the easiest & most flavorful toast recipe ever.",
          serves: "1",
          prep_time: "5 minutes",
          cook_time: "5 minutes",
          ingredients: JSON.stringify([
            "1 slice sourdough bread, sliced 1-1 ½ inches thick",
            "1 garlic clove, peeled",
            "1 small Roma tomato",
          ]),
          method: JSON.stringify([
            "In a toaster or your oven, toast your bread until crisp and golden brown.",
            "Slice the top off the garlic clove and rub the hot toasted bread with the garlic to infuse the bread with garlic flavor.",
            "Cut off the end of the tomato and rub it on the bread flesh side down, letting the tomato break apart on the bread. It will soak the bread in tomato, leaving behind some of its flesh and all of its flavor. Season with salt. Serve and enjoy.",
          ]),
          category: "Appetizer",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 41,
          title: "Grilled Cheese Sandwich",
          description:
            "The easiest and best Grilled Cheese Sandwich recipe ever.",
          serves: "1",
          prep_time: "2 minutes",
          cook_time: "8-10 minutes",
          ingredients: JSON.stringify([
            "2 slices milk bread (or your favorite white bread)",
            "2 tablespoons (28g) unsalted butter, room temperature",
            "2 slices American cheese",
          ]),
          method: JSON.stringify([
            "Set a 10-inch nonstick pan over medium heat. Once hot, add one tablespoon of butter and once melted, place one slice of bread in the butter to toast, making sure it’s fully coated. Top with both slices of American cheese and your second slice of bread.",
            "Reduce the heat to medium-low and toast until the bottom slice of bread is golden brown, about 2-3 minutes. Add the remaining butter to the pan and once melted, flip the sandwich and toast until golden brown, another 2-3 minutes. You can flip the sandwich again if you want the bread even darker or add a lid if you find the cheese isn’t melting enough for your liking. Remove your sandwich from the pan, slice on the diagonal, and serve and enjoy.",
          ]),
          category: "Lunch",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 42,
          title: "Blackberry Jam",
          description: "The easiest 3-ingredient blackberry jam recipe ever.",
          serves: "4",
          prep_time: "5 minutes",
          cook_time: "10 minutes, plus cooling",
          ingredients: JSON.stringify([
            "1 quart (2 pints) fresh blackberries",
            "¾ cup (150g) sugar",
            "¼ cup (60g) water",
            "1-2 tablespoons (15-30g) lemon juice",
          ]),
          method: JSON.stringify([
            "Combine blackberries and sugar in a medium saucepan. Smash the berries using your hands or a fork to break them down and macerate them with the sugar. Add the water and bring to a boil over medium-high heat. Reduce to a simmer and cook for 15-20 minutes or until the liquid is reduced and thickened, stirring occasionally. You can check the thickness by pouring about 1 teaspoon, or 4 grams, on a small plate, and placing it in the fridge for 1 minute. If after one minute it forms a sticky string when rubbed between two fingers, it’s done.",
            "Once the jam has thickened, stir in the lemon juice to taste. Pass the jam through a fine-mesh strainer and let it cool completely. Serve and enjoy.",
          ]),
          category: "Condiment",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 43,
          title: "Nigiri",
          description: "Making nigiri sushi at home has never been this easy.",
          serves: "4",
          prep_time: "4-8 hours",
          cook_time: "25 minutes",
          ingredients: JSON.stringify([
            "6 ounces (170g) sushi grade salmon loin",
            "1 cup (195g) sushi rice (Koshikari recommended)",
            "Sushi vinegar, to taste",
            "Salt, to taste",
          ]),
          method: JSON.stringify([
            "Cure your fish by evenly coating the entire piece with salt, setting it on a wire rack, and covering it with a damp paper towel, and then refrigerate for 12 hours.",
            "To make the sushi rice, begin by rinsing and washing the rice three times until the water runs clear. Place equal parts of rice to water into a rice cooker. Let the rice sit in the water for 15 minutes before cooking. Press start and cook.",
            "Once the rice is cooked, add it to a large bowl or hangiri and break up the rice with a large spoon or paddle making sure not to mash the rice. Sprinkle the sushi vinegar over the rice to taste. Using the paddle, lift and spread the rice towards the outside of the bowl or hangiri. Then using a damp towel, grab the edge of the bowl or hangiri and spin while paddling rice into a light ball in one spot. You can then keep the rice warm in the rice cooker if you’re not immediately using it.",
            "Slice your cured loin into ¼-inch slices against the grain, making sure to slice through the fish from the heel to the tip of your knife. Be careful not to press down with the knife and damage your fish.",
            "To assemble the nigiri, have a small bowl with cold water near a clean cutting board. Using dampened hands, take about 2 tablespoons of rice and form it into an oblong ball, similar to the shape of an egg, and place the sliced fish on top. Serve and enjoy.",
          ]),
          category: "Dinner",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 44,
          title: "Spanish Tortilla",
          description: "The easiest Spanish Tortilla-inspired recipe ever.",
          serves: "4-6",
          prep_time: "15 minutes",
          cook_time: "35 minutes",
          ingredients: JSON.stringify([
            "½ cup (107g) olive oil",
            "1 ½-2 lbs (680g-906g) Yukon Gold potatoes, peeled and thinly sliced on a mandoline",
            "6 eggs, seasoned to taste with salt and whisked",
            "Salt, to taste",
          ]),
          method: JSON.stringify([
            "Preheat your oven to 375°F (190°C).",
            "To a 12-inch non-stick skillet set over medium-high heat, add ¾ of your oil, and once hot, reduce heat to medium low and layer in your potatoes. Season to taste with salt, and top with remaining olive oil. Cook until the potatoes are soft, about 15-20 minutes. Season to taste with salt before pouring your eggs over your potatoes.",
            "Place your pan into the oven to fully cook the eggs, about 8-10 minutes.",
            "Let the tortilla rest for 5 minutes before cutting and serving.",
          ]),
          category: "Breakfast",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 45,
          title: "Pizza",
          description: "Homemade pizza has never been easier.",
          serves: "2-4",
          prep_time: "10 minutes",
          cook_time: "10-12 minutes",
          ingredients: JSON.stringify([
            "1 can (28oz) whole peeled San Marzano tomatoes, strained juice discarded",
            "1 ball pre-made pizza dough (Trader Joe’s recommended)",
            "4 cups (360g) low moisture mozzarella, freshly grated",
          ]),
          method: JSON.stringify([
            "Preheat an outdoor pizza oven to 700°F (370°C). If using a home oven, place a baking stone, or overturned baking sheet into a cold oven. Then preheat the oven to its maximum temperature for 30 minutes.",
            "To a blender, add your strained tomatoes. Make sure to only use the flesh, not the juice from the can, or your sauce will be too watery. Blend on low until pureed and as smooth as possible.",
            "Place your dough on the pizza peel. Press your fist into the center of the dough and begin to stretch the dough, leaving a border around the perimeter which will become the crust. Quarter turn the dough after each stretch, until you get roughly a 10-12 inch circle. Spread the pureed tomato sauce evenly over the dough, stopping short of the perimeter. Evenly cover the sauce with your cheese. mozzarella. Place pizza in the oven using the pizza peel.",
            "If using an outdoor pizza oven, cook for 20-30 seconds until one side begins to char. Quickly turn the pizza 180 degrees and cook for another 20-30 seconds. Do a quarter turn on the pizza and cook for 15 more seconds.",
            "If using a home oven, place the pizza onto the baking stone or baking sheet and bake for 8-10 minutes.",
            "Remove from the oven, season with salt and let sit for 1-2 minutes to set, then slice and enjoy.",
          ]),
          category: "Dinner",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 46,
          title: "Nutella Brownies",
          description:
            "Maybe the greatest brownie you can make in under 30 minutes.",
          serves: "6-8",
          prep_time: "5 minutes, plus cooling",
          cook_time: "20 minutes",
          ingredients: JSON.stringify([
            "1 lb (453g) Nutella",
            "3 large eggs",
            "¾ cup (112g) all-purpose flour",
            "Pinch of salt",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 350°F (176°C).",
            "In a large bowl whisk together the Nutella and eggs. Stir in the flour and salt until fully combined.",
            "Into an 8x8 non-stick baking dish, pour your batter and bake for 14-16 minutes until set or until a toothpick inserted comes out clean. Let cool to room temp before cutting. Serve and enjoy.",
          ]),
          category: "Dessert",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 47,
          title: "Peanut Butter Cookies",
          description: "Maybe the easiest cookie recipe of all-time.",
          serves: "6-8",
          prep_time: "10 minutes",
          cook_time: "12 minutes",
          ingredients: JSON.stringify([
            "1 cup (256g) creamy peanut butter",
            "1 cup (200g) sugar",
            "1 whole egg",
          ]),
          method: JSON.stringify([
            "Preheat the oven to 350°F (176°C).",
            "To a large mixing bowl, using a hand mixer, beat together the peanut butter and sugar until creamy, about 2-3 minutes. Add the egg and continue to mix for another minute until fully incorporated.",
            "Using a tablespoon or regular spoon, scoop cookie dough and form into balls and place them evenly on a parchment paper-lined cookie sheet, about 8 cookies per cookie sheet. Press each round down with a fork twice in the shape of a plus sign to form a nice pattern.",
            "Bake the cookies for 10-12 minutes. Allow them to cool before serving.",
          ]),
          category: "Dessert",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 48,
          title: "Red Curry Pork Chops",
          description: "The easiest 3-ingredient red curry pork recipe ever.",
          serves: "2",
          prep_time: "5 minutes",
          cook_time: "10 minutes",
          ingredients: JSON.stringify([
            "2x (1 ½-inch) thick pork chops, cut into 1-inch cubes, fat cap removed",
            "⅓ cup (85g) red curry paste",
            "1x can or 2 cups (480g) coconut milk, full fat unsweetened",
          ]),
          method: JSON.stringify([
            "Heat a large saute pan over medium-low heat. Using your hand or a pair of tongs, rub the fat cap around the pan until fully coated in a thin layer of fat. This will be the cooking oil you use to sear the pork. Increase the heat to medium high and add your pork to the pan in one layer, and sear for 1-2 minutes. Flip each piece one time, season to taste with salt, and sear another 2 minutes. Remove the pork from the pan and set aside to drain on a wire rack atop a small sheet pan.",
            "Using the same saute pan with the pork fond intact, reduce the heat to medium and add the curry paste. With a spoon stir the paste around the pan and cook for 1-2 minutes until the paste is dark red. Increase the heat to medium-high, add the coconut milk and scrape the bottom of the pan to release the fond. Bring to a boil, add in your pork, and reduce the heat to medium low and simmer until the pork is fully cooked through, about 3-4 minutes. Serve and enjoy.",
          ]),
          category: "Dinner",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 49,
          title: "Garlic and Olive Oil Pasta (Aglio e Olio)",
          description: "The easiest 3-ingredient garlicky pasta recipe ever.",
          serves: "4",
          prep_time: "10 minutes",
          cook_time: "10-12 minutes",
          ingredients: JSON.stringify([
            "½ cup (112g) olive oil",
            "12 cloves garlic, thinly sliced",
            "1 lb (453g) bucatini or spaghetti",
          ]),
          method: JSON.stringify([
            "Place bucatini in a large 6-8 quart pot of boiling water that has been seasoned generously with salt. Cook according to package instructions or until cooked al dente, about 7 minutes. Drain the pasta but reserve ½ cup of the pasta water.",
            "While the water is boiling, to a separate, cold, 5-quart saucepan add your olive oil and garlic. Heat to medium-low and until the garlic is slightly sizzling and golden brown, about 3-4 minutes and then turn off the heat. Make sure to stir the garlic while it cooks so it does not burn. If the garlic does burn, it will turn bitter and I would recommend throwing it away and starting again.",
            "Once the pasta is cooked, return the heat on your saucepan to medium-low and using tongs add the pasta and a spoonful of pasta water to the warm oil and garlic slices. Toss to coat until emulsified, adjust with one spoonful at a time of reserved pasta water as needed, and salt to taste. Toss one more time to ensure the pasta is fully coated in the sauce.",
            "Plate and top with a few golden garlic slices. Serve and enjoy.",
          ]),
          category: "Dinner",
          rating: 4.5,
          image_path: "",
        },
        {
          id: 50,
          title: "Steak and Eggs",
          description: "The easiest way to upgrade your steak & eggs recipe.",
          serves: "1",
          prep_time: "2 minutes",
          cook_time: "20 minutes",
          ingredients: JSON.stringify([
            "1x 1.5 pound (680g) 1-inch thick boneless ribeye steak, fat cap removed and diced, to be rendered and used for cooking oil",
            "Salt, to taste",
            "Freshly cracked black pepper, to taste *optional",
            "1 egg",
            "Spicy chili crisp, to taste",
          ]),
          method: JSON.stringify([
            "Pre-heat a 10-inch stainless-steel pan or cast-iron skillet over medium heat. Add the diced fat cap to the pan to render the fat and remove when your pan is coated in a nice, thin layer of oil. Increase the heat to medium-high.",
            "Pat the ribeye steak dry with a paper towel. Season one side of the steak generously with kosher salt and, optionally, with fresh cracked black pepper.",
            "Add the steak to your pan or skillet and press down for full contact. Season with kosher salt to taste. Sear for 2-3 minutes per side until internal temperature of 135°F (60°C). The steaks should be medium rare, but if they’re still too rare, reduce the heat to medium, and cook, flipping constantly, until they reach medium-rare.",
            "Remove the steaks from the pan and set them on a cutting board to rest, about 5-10 minutes.",
            "While the steak rests, add the egg to your pan or skillet, season to taste with salt, and fry to your liking. If there is enough fat in the pan, tilt the pan toward you and using a spoon, baste the egg whites with the fat for about 30 seconds until cooked.",
            "Place the egg on top of the steak and drizzle with chili crisp to taste. You could replace the chili crisp with any hot sauce you like. Serve and enjoy.",
          ]),
          category: "Breakfast",
          rating: 4.5,
          image_path: "",
        },
      ]);
    });
};
